# Iterando com DataFrames

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('db.csv', sep=';', index_col = 0)

In [3]:
dataset.head()

                            Motor  ...      Valor
Nome                               ...
Jetta Variant     Motor 4.0 Turbo  ...   88078.64
Passat               Motor Diesel  ...  106161.94
Crossfox          Motor Diesel V8  ...   72832.16
DS5               Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4  Motor 2.4 Turbo  ...   92612.10

[5 rows x 6 columns]

In [4]:
for item in dataset:
  print(item)

Motor
Ano
Quilometragem
Zero_km
Acessórios
Valor

In [5]:
dataset.iterrows()

In [6]:
for index, row in dataset.iterrows():
  if(2019 - row['Ano'] != 0):
    dataset.loc[index, 'km_media'] = row['Quilometragem'] / (2019 - row['Ano'])
  else:
    dataset.loc['index', 'km_media'] =  0 

dataset

                                       Motor     Ano  ...      Valor     km_media
Nome                                                  ...
Jetta Variant                Motor 4.0 Turbo  2003.0  ...   88078.64  2775.625000
Passat                          Motor Diesel  1991.0  ...  106161.94   204.000000
Crossfox                     Motor Diesel V8  1990.0  ...   72832.16  1280.103448
DS5                          Motor 2.4 Turbo  2019.0  ...  124549.07          NaN
Aston Martin DB4             Motor 2.4 Turbo  2006.0  ...   92612.10  1981.307692
...                                      ...     ...  ...        ...          ...
Cadillac Ciel concept               Motor V8  1991.0  ...   51667.06  1070.750000
Classe GLK             Motor 5.0 V8 Bi-Turbo  2002.0  ...   68934.03  3096.294118
Aston Martin DB5                Motor Diesel  1996.0  ...  122110.90   334.130435
Macan                        Motor Diesel V6  1992.0  ...   90381.47  1858.814815
index                                    NaN     NaN  ...        NaN     0.000000

[259 rows x 7 columns]

# Tratamento de dados

In [7]:
dataset.head()

                            Motor     Ano  ...      Valor     km_media
Nome                                       ...
Jetta Variant     Motor 4.0 Turbo  2003.0  ...   88078.64  2775.625000
Passat               Motor Diesel  1991.0  ...  106161.94   204.000000
Crossfox          Motor Diesel V8  1990.0  ...   72832.16  1280.103448
DS5               Motor 2.4 Turbo  2019.0  ...  124549.07          NaN
Aston Martin DB4  Motor 2.4 Turbo  2006.0  ...   92612.10  1981.307692

[5 rows x 7 columns]

In [8]:
#verificando informações do dataset
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 259 entries, Jetta Variant to index
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Motor          258 non-null    object
 1   Ano            258 non-null    float64
 2   Quilometragem  197 non-null    float64
 3   Zero_km        258 non-null    object
 4   Acessórios     258 non-null    object
 5   Valor          258 non-null    float64
 6   km_media       198 non-null    float64
dtypes: float64(4), object(3)
memory usage: 26.2+ KB

In [9]:
#verificando not a number
dataset.Quilometragem.isna()

Nome
Jetta Variant            False
Passat                   False
Crossfox                 False
DS5                       True
Aston Martin DB4         False
                         ...
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5         False
Macan                    False
index                     True
Name: Quilometragem, Length: 259, dtype: bool

In [10]:
#identificando em quais linhas possuem NaN
dataset[dataset.Quilometragem.isna()]

                      Motor     Ano  ...      Valor km_media
Nome                                 ...
DS5         Motor 2.4 Turbo  2019.0  ...  124549.07      NaN
A5          Motor 4.0 Turbo  2019.0  ...   56445.20      NaN
J5                 Motor V6  2019.0  ...   53183.38      NaN
A3             Motor 1.0 8v  2019.0  ...   88552.39      NaN
Série 1 M          Motor V8  2019.0  ...   94564.40      NaN
...                     ...     ...  ...        ...      ...
Benni Mini         Motor V8  2019.0  ...  126247.84      NaN
Uno         Motor Diesel V6  2019.0  ...  128852.21      NaN
Santa Fe      Motor 3.0 32v  2019.0  ...  129415.33      NaN
XC60        Motor 4.0 Turbo  2019.0  ...   77675.79      NaN
index                   NaN     NaN  ...        NaN      0.0

[62 rows x 7 columns]

In [11]:
#substituindo NaN por 0
dataset.fillna(0, inplace=True)

In [14]:
#utilizando query para consultar os dados alterados
dataset.query('Zero_km == True')

                                Motor     Ano  ...      Valor km_media
Nome                                           ...
DS5                   Motor 2.4 Turbo  2019.0  ...  124549.07      0.0
A5                    Motor 4.0 Turbo  2019.0  ...   56445.20      0.0
J5                           Motor V6  2019.0  ...   53183.38      0.0
A3                       Motor 1.0 8v  2019.0  ...   88552.39      0.0
Série 1 M                    Motor V8  2019.0  ...   94564.40      0.0
...                               ...     ...  ...        ...      ...
Lamborghini Reventón  Motor 4.0 Turbo  2019.0  ...   67664.86      0.0
Benni Mini                   Motor V8  2019.0  ...  126247.84      0.0
Uno                   Motor Diesel V6  2019.0  ...  128852.21      0.0
Santa Fe                Motor 3.0 32v  2019.0  ...  129415.33      0.0
XC60                  Motor 4.0 Turbo  2019.0  ...   77675.79      0.0

[61 rows x 7 columns]

In [15]:
#gerando um dataset com base no origial
dataset = pd.read_csv('db.csv', sep=';')

      Nome  Motor    Ano  Quilometragem  Zero_km  Acessórios  Valor
0    False  False  False          False    False       False  False
1    False  False  False          False    False       False  False
2    False  False  False          False    False       False  False
3    False  False  False           True    False       False  False
4    False  False  False          False    False       False  False
..     ...    ...    ...            ...      ...         ...    ...
253  False  False  False          False    False       False  False
254  False  False  False          False    False       False  False
255  False  False  False          False    False       False  False
256  False  False  False          False    False       False  False
257  False  False  False          False    False       False  False

[258 rows x 7 columns]

In [18]:
#deletando rows com NaN
dataset.dropna(subset = ['Quilometragem'])

                      Nome  ...      Valor
0            Jetta Variant  ...   88078.64
1                   Passat  ...  106161.94
2                 Crossfox  ...   72832.16
4         Aston Martin DB4  ...   92612.10
5            Palio Weekend  ...   97497.73
..                     ...  ...        ...
253           Phantom 2013  ...   51759.58
254  Cadillac Ciel concept  ...   51667.06
255             Classe GLK  ...   68934.03
256       Aston Martin DB5  ...  122110.90
257                  Macan  ...   90381.47

[197 rows x 7 columns]