# Pandas básico

# Series

Series são arrays unidimensionais rotulados e capazes de armazenar qualquer arquivo. Os rótulos das linhas são chamados de **index**. A forma básica de criação de uma Series é a seguinte.

|

s = pd.Series(dados, index = index)

# DataFrames

DataFrame é uma estrutura de dados tabular bidimensional com rótulos nas linhas e colunas. Como a Series, os DataFrames são capazes de armazenar qualquer tipo de dados.

|

df = pd.DataFrame(dados, index = index, columns = columns)

# Estruturas de dados

In [1]:
import pandas as pd

In [2]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']

In [3]:
pd.Series(carros)

0    Jetta Variant
1           Passat
2         Crossfox
dtype: object

# Criando um DataFrame a partir de uma lista de dicionários

In [4]:
dados = [
    {'Nome': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Ano': 2003, 'Quilometragem': 44410.0, 'Zero_km': False, 'Valor': 88078.64},
    {'Nome': 'Passat', 'Motor': 'Motor Diesel', 'Ano': 1991, 'Quilometragem': 5712.0, 'Zero_km': False, 'Valor': 106161.94},
    {'Nome': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Ano': 1990, 'Quilometragem': 37123.0, 'Zero_km': False, 'Valor': 72932.16}
]

In [5]:
pd.DataFrame(dados)

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72932.16

# Criando DataFrame a partir de um dicionário

In [6]:
dados = {
    'Nome': ['Jetta Variant', 'Passat', 'Crossfox'],
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8'],
    'Ano': [2003, 1991, 1990],
    'Zero_km': [False, False, False],
    'Valor': [88078.64, 106161.94, 72932.16]
    }

In [7]:
pd.DataFrame(dados)

            Nome            Motor   Ano  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003    False   88078.64
1         Passat     Motor Diesel  1991    False  106161.94
2       Crossfox  Motor Diesel V8  1990    False   72932.16

# **!!** Criando DataFrame a partir de um arquivo externo **!!**

In [9]:
dataset = pd.read_csv('db.csv', sep=';')

In [10]:
dataset

                      Nome  ...      Valor
0            Jetta Variant  ...   88078.64
1                   Passat  ...  106161.94
2                 Crossfox  ...   72832.16
3                      DS5  ...  124549.07
4         Aston Martin DB4  ...   92612.10
..                     ...  ...        ...
253           Phantom 2013  ...   51759.58
254  Cadillac Ciel concept  ...   51667.06
255             Classe GLK  ...   68934.03
256       Aston Martin DB5  ...  122110.90
257                  Macan  ...   90381.47

[258 rows x 7 columns]