# Queries com DataFrames

In [12]:
import pandas as pd

In [13]:
dataset = pd.read_csv('db.csv', sep=';', index_col = 0)

In [14]:
dataset.head()

                            Motor  ...      Valor
Nome                               ...
Jetta Variant     Motor 4.0 Turbo  ...   88078.64
Passat               Motor Diesel  ...  106161.94
Crossfox          Motor Diesel V8  ...   72832.16
DS5               Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4  Motor 2.4 Turbo  ...   92612.10

[5 rows x 6 columns]

In [15]:
dataset.shape

(258, 6)

In [16]:
dataset.Motor

Nome
Jetta Variant                  Motor 4.0 Turbo
Passat                            Motor Diesel
Crossfox                       Motor Diesel V8
DS5                            Motor 2.4 Turbo
Aston Martin DB4               Motor 2.4 Turbo
                                 ...
Phantom 2013                          Motor V8
Cadillac Ciel concept                 Motor V8
Classe GLK               Motor 5.0 V8 Bi-Turbo
Aston Martin DB5                  Motor Diesel
Macan                          Motor Diesel V6
Name: Motor, Length: 258, dtype: object

In [18]:
select = dataset.Motor == 'Motor Diesel'

In [21]:
dataset[select]

                              Motor  ...      Valor
Nome                                 ...
Passat                 Motor Diesel  ...  106161.94
Effa Hafei Picape Baú  Motor Diesel  ...  125684.65
Sorento                Motor Diesel  ...   81399.35
New Fiesta Hatch       Motor Diesel  ...   66007.16
Kangoo Express         Motor Diesel  ...  146716.91
Fit                    Motor Diesel  ...   77836.23
Cielo Hatch            Motor Diesel  ...  145197.70
Symbol                 Motor Diesel  ...  133030.60
A4 Sedan               Motor Diesel  ...   96369.04
A4 Avant               Motor Diesel  ...  138946.88
Silver Shadow          Motor Diesel  ...  143568.22
Camry                  Motor Diesel  ...  138597.27
Clio                   Motor Diesel  ...  111130.33
Série 3 M3 Coupé       Motor Diesel  ...   69219.89
Gallardo LP 560 – 4    Motor Diesel  ...  144118.91
Chana Utility          Motor Diesel  ...  132662.32
TT Roadster            Motor Diesel  ...   85311.40
Aston Martin Virage    Motor Diesel  ...   97290.18
Sandero                Motor Diesel  ...  112350.61
XKR                    Motor Diesel  ...   54263.16
X5                     Motor Diesel  ...   62041.32
Dodge Dakota           Motor Diesel  ...  141083.35
i30 CW                 Motor Diesel  ...   73311.75
Série 7 Sedã           Motor Diesel  ...   67539.79
V60                    Motor Diesel  ...  114728.74
Aston Martin DB5       Motor Diesel  ...  122110.90

[26 rows x 6 columns]

In [24]:
#consultando dados entre as seguintes filtragens 
dataset[(dataset.Motor == 'Motor Diesel') & (dataset.Zero_km == True)]

                            Motor  ...      Valor
Nome                               ...
Sorento              Motor Diesel  ...   81399.35
Cielo Hatch          Motor Diesel  ...  145197.70
Camry                Motor Diesel  ...  138597.27
Aston Martin Virage  Motor Diesel  ...   97290.18
Série 7 Sedã         Motor Diesel  ...   67539.79

[5 rows x 6 columns]

# Utilizando o método query

In [26]:
dataset.query('Motor == "Motor Diesel" and Zero_km == True')

                            Motor  ...      Valor
Nome                               ...
Sorento              Motor Diesel  ...   81399.35
Cielo Hatch          Motor Diesel  ...  145197.70
Camry                Motor Diesel  ...  138597.27
Aston Martin Virage  Motor Diesel  ...   97290.18
Série 7 Sedã         Motor Diesel  ...   67539.79

[5 rows x 6 columns]