In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('db.csv', sep=';', index_col = 0)

In [3]:
dataset.head()

                            Motor  ...      Valor
Nome                               ...
Jetta Variant     Motor 4.0 Turbo  ...   88078.64
Passat               Motor Diesel  ...  106161.94
Crossfox          Motor Diesel V8  ...   72832.16
DS5               Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4  Motor 2.4 Turbo  ...   92612.10

[5 rows x 6 columns]

In [11]:
#selecionando coluna
dataset['Valor']

Nome
Jetta Variant             88078.64
Passat                   106161.94
Crossfox                  72832.16
DS5                      124549.07
Aston Martin DB4          92612.10
                           ...
Phantom 2013              51759.58
Cadillac Ciel concept     51667.06
Classe GLK                68934.03
Aston Martin DB5         122110.90
Macan                     90381.47
Name: Valor, Length: 258, dtype: float64

In [13]:
type(dataset['Valor'])

pandas.core.series.Series

In [15]:
#selecionando duas colunas
dataset[['Ano', 'Valor']]

                        Ano      Valor
Nome
Jetta Variant          2003   88078.64
Passat                 1991  106161.94
Crossfox               1990   72832.16
DS5                    2019  124549.07
Aston Martin DB4       2006   92612.10
...                     ...        ...
Phantom 2013           2014   51759.58
Cadillac Ciel concept  1991   51667.06
Classe GLK             2002   68934.03
Aston Martin DB5       1996  122110.90
Macan                  1992   90381.47

[258 rows x 2 columns]

In [16]:
#observacao2
type(dataset[['Ano', 'Valor']])

pandas.core.frame.DataFrame

# Selecionando linhas - [i:j]

**Observação:** A indexação tem origem no zero e nos fatiamentos (slices) a linha com índice i é **incluída** e a linha com índice j **não é incluida** no resultado.

In [7]:
dataset[:3]

                         Motor  ...      Valor
Nome                            ...
Jetta Variant  Motor 4.0 Turbo  ...   88078.64
Passat            Motor Diesel  ...  106161.94
Crossfox       Motor Diesel V8  ...   72832.16

[3 rows x 6 columns]

# Utilizando o *.loc* para seleções

In [8]:
dataset

                                       Motor  ...      Valor
Nome                                          ...
Jetta Variant                Motor 4.0 Turbo  ...   88078.64
Passat                          Motor Diesel  ...  106161.94
Crossfox                     Motor Diesel V8  ...   72832.16
DS5                          Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4             Motor 2.4 Turbo  ...   92612.10
...                                      ...  ...        ...
Phantom 2013                        Motor V8  ...   51759.58
Cadillac Ciel concept               Motor V8  ...   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo  ...   68934.03
Aston Martin DB5                Motor Diesel  ...  122110.90
Macan                        Motor Diesel V6  ...   90381.47

[258 rows x 6 columns]

In [18]:
dataset.loc['Passat']

Motor                                                 Motor Diesel
Ano                                                           1991
Quilometragem                                                 5712
Zero_km                                                      False
Acessórios       ['Central multimídia', 'Teto panorâmico', 'Fre...
Valor                                                       106162
Name: Passat, dtype: object

In [21]:
#filtragem [[index_1, index_2], [column_1, column_2]]
dataset.loc[['Passat', 'DS5'], ['Motor', 'Valor']]

                  Motor      Valor
Nome
Passat     Motor Diesel  106161.94
DS5     Motor 2.4 Turbo  124549.07

In [22]:
#filtragem de dados [index, [column_1, column_2]]
dataset.loc[:, ['Motor', 'Valor']]

                                       Motor      Valor
Nome
Jetta Variant                Motor 4.0 Turbo   88078.64
Passat                          Motor Diesel  106161.94
Crossfox                     Motor Diesel V8   72832.16
DS5                          Motor 2.4 Turbo  124549.07
Aston Martin DB4             Motor 2.4 Turbo   92612.10
...                                      ...        ...
Phantom 2013                        Motor V8   51759.58
Cadillac Ciel concept               Motor V8   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo   68934.03
Aston Martin DB5                Motor Diesel  122110.90
Macan                        Motor Diesel V6   90381.47

[258 rows x 2 columns]

# Utilizando *.iloc* para seleções

**Observação:** Seleciona com base nos índices, ou seja, se baseia na posição das informações.

Localização baseada em indexação númerica.

In [26]:
dataset.head()

                            Motor  ...      Valor
Nome                               ...
Jetta Variant     Motor 4.0 Turbo  ...   88078.64
Passat               Motor Diesel  ...  106161.94
Crossfox          Motor Diesel V8  ...   72832.16
DS5               Motor 2.4 Turbo  ...  124549.07
Aston Martin DB4  Motor 2.4 Turbo  ...   92612.10

[5 rows x 6 columns]

In [27]:
dataset.iloc[1:4]

                    Motor  ...      Valor
Nome                       ...
Passat       Motor Diesel  ...  106161.94
Crossfox  Motor Diesel V8  ...   72832.16
DS5       Motor 2.4 Turbo  ...  124549.07

[3 rows x 6 columns]

In [28]:
dataset.iloc[1:4, [0, 5, 2]]

                    Motor      Valor  Quilometragem
Nome
Passat       Motor Diesel  106161.94         5712.0
Crossfox  Motor Diesel V8   72832.16        37123.0
DS5       Motor 2.4 Turbo  124549.07            NaN

In [31]:
dataset.iloc[[1, 42, 22], [0, 5, 2]]

                               Motor      Valor  Quilometragem
Nome
Passat                  Motor Diesel  106161.94         5712.0
Optima                 Motor 1.8 16v   86641.34            NaN
Lamborghini Obvious  Motor Diesel V6  133529.84        98079.0